SELECT seller_state,
       COUNT(DISTINCT SELLER_ID) AS QTDE_VENDEDORES

FROM TB_SELLERS

-- FILTRO PRÉ AGREGAÇÃO
WHERE seller_state IN ('SP', 'RJ', 'PR', 'AC')

-- AGREGAÇÃO
GROUP BY seller_state

-- FILTRO PÓS AGREGAÇÃO
-- SE VOCE NAO TEM GROUP BY NAO FAZ SENTIO TER O HAVING
HAVING COUNT(*) > 10